### ISSUE TITLE
Integrate voting panel with GraviolaSeasonsGovernor

### ISSUE THREAD

**Issue by el-tumero** [el-tumero/graviola#95]
Use useWallet hook to integrate GraviolaSeasonsGovernor with voting panel.
Handle transactions, events and errors - add popups or any custom component for providing info for user about the process.

Available Graviola Seasons Governor features:
https://github.com/el-tumero/graviola/wiki/Contracts#graviola-seasons-governor

**Comment by teavver** [comment]
Postponed to mainnet release, closing for now.
